default-target = "wasm32-unknown-emscripten"

[target.emscripten]
link-args = ["-s", "EXPORTED_FUNCTIONS=['_execute_lua']", "-s", "ASSERTIONS=1", "-s", "EXTRA_EXPORTED_RUNTIME_METHODS=['cwrap','addOnInit','ccall','FS']"]
